data_types = {
    'tv':{
        'settlement_id': 'float',
        'settlement_start_date': 'datetime64',
        'settlement_end_date': 'datetime64',
        'deposit_date': 'datetime64',
        'total_amount': 'float',
        'currency': 'str',
        'transaction_type': 'str',
        'order_id': 'str',
        'merchant_order_id': 'str',
        'adjustment_id': 'str',
        'shipment_id': 'str',
        'marketplace_name': 'str',
        'amount_type': 'str',
        'amount_description': 'str',
        'amount': 'float',
        'fulfillment_id': 'str',
        'posted_date': 'datetime64',
        'posted_date_time': 'datetime64',
        'order_item_code': 'str',
        'merchant_order_item_id': 'str',
        'merchant_adjustment_item_id': 'float',
        'sku': 'str',
        'quantity_purchased': 'float',
        'promotion_id': 'str'
    },
    'oc':{
        "amazon_order_id": "str",
        "merchant_order_id": "str",
        "purchase_date": "datetime64",
        "last_updated_date": "datetime64",
        "order_status": "str",
        "fulfillment_channel": "str",
        "sales_channel": "str",
        "order_channel": "str",
        "url": "str",
        "ship_service_level": "str",
        "product_name": "str",
        "sku": "str",
        "asin": "str",
        "item_status": "str",
        "quantity": "int64",
        "currency": "str",
        "item_price": "float",
        "item_tax": "float",
        "shipping_price": "float",
        "shipping_tax": "float",
        "gift_wrap_price": "float",
        "gift_wrap_tax": "float",
        "item_promotion_discount": "float",
        "ship_promotion_discount": "float",
        "ship_city": "str",
        "ship_state": "str",
        "ship_postal_code": "str",
        "ship_country": "str",
        "promotion_ids": "str",
    }
}
